Sdk 2.0
mangata-finance/mangata-sdk pull request #76
Opened 2023-04-27 08:01 UTC by devdanco

2023-05-04 06:42 UTC, DominikFedor requested changes

2023-05-04 06:42 UTC, DominikFedor commented on src/mangata.ts
> +        await getAmountOfTokenIdInPool(
`getAmountOfTokensInPool` might be better name. Ids as params are explanatory enough

2023-05-04 06:42 UTC, DominikFedor commented on src/utils/calculateFutureRewardsAmountForMinting.ts
>  export const calculateFutureRewardsAmountForMinting = async (
`calculateMintingFutureRewards` might be enough and shorter

2023-05-04 06:42 UTC, DominikFedor commented on src/utils/getTxError.ts
> +export const getError = (
`getTxError` would be more explanatory

2023-05-04 15:52 UTC, DominikFedor submitted a review, later dismissed

2023-05-05 13:18 UTC, matusbalascak submitted a review, later dismissed

2023-06-16 09:44 UTC, matusbalascak approved these changes

2023-06-16 10:02 UTC, closed without merging